version: "3"

services:
  app_base:
    build: ./services/base/.
    container_name: app_base
    restart: always
    networks:
      - app
    volumes:
      - ./services/base/logs.txt:/app/logs.txt
      - ./common:/app/common
      - ./database:/app/database
    ports:
      - 9999:1111


#  alembic:
#    build: ./alembic/.
#    restart: on-failure
#    networks:
#      - app
#    volumes:
#      - ./.env:/app/.env
#      - ./common/:/app/common
#      - ./database:/app/database
#      - ./alembic/:/app/alembic
#      - ./alembic.ini/:/app/alembic.ini
#    command: alembic upgrade head

networks:
  app:
    driver: bridge
